--  DaDaPush Public API
--  DaDaPush: Real_time Notifications App Send real_time notifications through our API without coding and maintaining your own app for iOS or Android devices.
--
--  The version of the OpenAPI document: v1
--  Contact: contacts@dadapush.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 4.0.2.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Swagger.Streams;
with Ada.Containers.Vectors;
package .Models is


   --  ------------------------------
   --  Action
   --  ------------------------------
   type ActionType is
     record
       Name : Swagger.UString;
       P_Type : Swagger.UString;
       Url : Swagger.UString;
     end record;

   package ActionType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => ActionType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ActionType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ActionType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ActionType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ActionType_Vectors.Vector);



   --  ------------------------------
   --  MessagePushRequest
   --  ------------------------------
   type MessagePushRequestType is
     record
       Actions : .Models.ActionType_Vectors.Vector;
       Content : Swagger.UString;
       Need_Push : Boolean;
       Title : Swagger.UString;
     end record;

   package MessagePushRequestType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => MessagePushRequestType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MessagePushRequestType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MessagePushRequestType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MessagePushRequestType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MessagePushRequestType_Vectors.Vector);



   --  ------------------------------
   --  MessageObject
   --  ------------------------------
   type MessageObjectType is
     record
       Actions : .Models.ActionType_Vectors.Vector;
       Channel_Name : Swagger.UString;
       Content : Swagger.UString;
       Created_At : Swagger.UString;
       Id : Swagger.Long;
       Title : Swagger.UString;
     end record;

   package MessageObjectType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => MessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MessageObjectType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MessageObjectType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MessageObjectType_Vectors.Vector);



   --  ------------------------------
   --  resultOfMessageObject
   --  ------------------------------
   type ResultOfMessageObjectType is
     record
       Code : Integer;
       Data : .Models.MessageObjectType;
       Errmsg : Swagger.UString;
     end record;

   package ResultOfMessageObjectType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => ResultOfMessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultOfMessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultOfMessageObjectType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultOfMessageObjectType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultOfMessageObjectType_Vectors.Vector);



   --  ------------------------------
   --  PageResponseOfMessageObject
   --  ------------------------------
   type PageResponseOfMessageObjectType is
     record
       Content : .Models.MessageObjectType_Vectors.Vector;
       Total_Elements : Swagger.Long;
       Total_Pages : Swagger.Long;
     end record;

   package PageResponseOfMessageObjectType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => PageResponseOfMessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in PageResponseOfMessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in PageResponseOfMessageObjectType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out PageResponseOfMessageObjectType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out PageResponseOfMessageObjectType_Vectors.Vector);



   --  ------------------------------
   --  resultOfPageResponseOfMessageObject
   --  ------------------------------
   type ResultOfPageResponseOfMessageObjectType is
     record
       Code : Integer;
       Data : .Models.PageResponseOfMessageObjectType;
       Errmsg : Swagger.UString;
     end record;

   package ResultOfPageResponseOfMessageObjectType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => ResultOfPageResponseOfMessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultOfPageResponseOfMessageObjectType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultOfPageResponseOfMessageObjectType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultOfPageResponseOfMessageObjectType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultOfPageResponseOfMessageObjectType_Vectors.Vector);



   --  ------------------------------
   --  MessagePushResponse
   --  ------------------------------
   type MessagePushResponseType is
     record
       Message_Id : Swagger.Long;
     end record;

   package MessagePushResponseType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => MessagePushResponseType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MessagePushResponseType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MessagePushResponseType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MessagePushResponseType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MessagePushResponseType_Vectors.Vector);



   --  ------------------------------
   --  resultOfMessagePushResponse
   --  ------------------------------
   type ResultOfMessagePushResponseType is
     record
       Code : Integer;
       Data : .Models.MessagePushResponseType;
       Errmsg : Swagger.UString;
     end record;

   package ResultOfMessagePushResponseType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => ResultOfMessagePushResponseType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultOfMessagePushResponseType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultOfMessagePushResponseType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultOfMessagePushResponseType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultOfMessagePushResponseType_Vectors.Vector);



   --  ------------------------------
   --  result
   --  ------------------------------
   type ResultType is
     record
       Code : Integer;
       Data : Swagger.Object;
       Errmsg : Swagger.UString;
     end record;

   package ResultType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => ResultType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in ResultType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out ResultType_Vectors.Vector);



end .Models;
